### ISSUE TITLE
Native audio playback on Android isn't working with the .NET MAUI Blazor app

### ISSUE THREAD

**Issue by danroth27** [microsoft/dotnet-podcasts#102]
Repro steps:
- Run the backend locally with Docker
- Run the MobileBlazor app
- Try playing a podcast

Expected result:
- Audio plays in the emulator and the native playback widget shows up in the top settings pane

Actual result:
- No audio plays. No platform playback widget shows up.

**Comment by migueBarrera** [comment]
Hi @danroth27 . 
I think the issue is that the audio is not under https.
By default, android does not work with urls without https.
The blazor app is prepared to work without https on domain 10.0.2.2. Have you changed the domain when you deploy the server? 
If you have changed it, you should update the NetPodsMauiBlazor/Platforms/Android/Resources/xml/network_security_config.xml file and use the new domain. 
If not, I'm not sure why it doesn't work, but I found a workaround, in this [branch](https://github.com/microsoft/dotnet-podcasts/tree/feature/blazor-android-audio-with-out-https), we allow all calls without https, this will work.

**Comment by migueBarrera** [comment]
Yo can review the changes here https://github.com/microsoft/dotnet-podcasts/pull/103

**Comment by danroth27** [comment]
> Are you trying to use it with the next-steps brach?

Yes

> Have you changed the domain when you deploy the server?

I'm running the backend locally using Docker.

> You can review the changes here https://github.com/microsoft/dotnet-podcasts/pull/103

@jamesmontemagno  I think we'll need someone on the .NET MAUI team to review this change as I am not familiar with these settings.

**Comment by migueBarrera** [comment]
could you try again with the next-steps branch? With [this merge](https://github.com/microsoft/dotnet-podcasts/pull/103) it should work.

**Comment by danroth27** [comment]
Works for me. I did have to update the API URL in the .NET MAUI project, but we can deal with that separately.
